// Mocks generated by Mockito 5.4.6 from annotations
// in reservaloya_admin/test/recurring_reservation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:dartz/dartz.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:reservaloya_admin/core/error/failures.dart' as _i13;
import 'package:reservaloya_admin/core/usecases/usecase.dart' as _i17;
import 'package:reservaloya_admin/features/dashboard/domain/entities/booking.dart'
    as _i14;
import 'package:reservaloya_admin/features/dashboard/domain/entities/sport_center.dart'
    as _i16;
import 'package:reservaloya_admin/features/dashboard/domain/repositories/dashboard_repository.dart'
    as _i4;
import 'package:reservaloya_admin/features/dashboard/domain/usecases/create_internal_booking_usecase.dart'
    as _i12;
import 'package:reservaloya_admin/features/dashboard/domain/usecases/get_admin_courts_usecase.dart'
    as _i15;
import 'package:reservaloya_admin/features/recurring/domain/entities/recurring_reservation.dart'
    as _i3;
import 'package:reservaloya_admin/features/recurring/domain/entities/recurring_series.dart'
    as _i8;
import 'package:reservaloya_admin/features/recurring/domain/repositories/recurring_repository.dart'
    as _i2;
import 'package:reservaloya_admin/features/recurring/domain/usecases/cancel_recurring_reservation_usecase.dart'
    as _i9;
import 'package:reservaloya_admin/features/recurring/domain/usecases/create_recurring_reservation_usecase.dart'
    as _i11;
import 'package:reservaloya_admin/features/recurring/domain/usecases/delete_series_usecase.dart'
    as _i10;
import 'package:reservaloya_admin/features/recurring/domain/usecases/get_recurring_series_usecase.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRecurringRepository_0 extends _i1.SmartFake
    implements _i2.RecurringRepository {
  _FakeRecurringRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRecurringReservation_1 extends _i1.SmartFake
    implements _i3.RecurringReservation {
  _FakeRecurringReservation_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDashboardRepository_2 extends _i1.SmartFake
    implements _i4.DashboardRepository {
  _FakeDashboardRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_3<L, R> extends _i1.SmartFake implements _i5.Either<L, R> {
  _FakeEither_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetRecurringSeriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRecurringSeriesUseCase extends _i1.Mock
    implements _i6.GetRecurringSeriesUseCase {
  MockGetRecurringSeriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RecurringRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeRecurringRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.RecurringRepository);

  @override
  _i7.Future<List<_i8.RecurringSeries>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i7.Future<List<_i8.RecurringSeries>>.value(
              <_i8.RecurringSeries>[],
            ),
          )
          as _i7.Future<List<_i8.RecurringSeries>>);
}

/// A class which mocks [CancelRecurringReservationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCancelRecurringReservationUseCase extends _i1.Mock
    implements _i9.CancelRecurringReservationUseCase {
  MockCancelRecurringReservationUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RecurringRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeRecurringRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.RecurringRepository);

  @override
  _i7.Future<void> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [DeleteSeriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteSeriesUseCase extends _i1.Mock
    implements _i10.DeleteSeriesUseCase {
  MockDeleteSeriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RecurringRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeRecurringRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.RecurringRepository);

  @override
  _i7.Future<void> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [CreateRecurringReservationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateRecurringReservationUseCase extends _i1.Mock
    implements _i11.CreateRecurringReservationUseCase {
  MockCreateRecurringReservationUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RecurringRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeRecurringRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.RecurringRepository);

  @override
  _i7.Future<_i3.RecurringReservation> call(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#call, [data]),
            returnValue: _i7.Future<_i3.RecurringReservation>.value(
              _FakeRecurringReservation_1(
                this,
                Invocation.method(#call, [data]),
              ),
            ),
          )
          as _i7.Future<_i3.RecurringReservation>);
}

/// A class which mocks [CreateInternalBookingUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateInternalBookingUseCase extends _i1.Mock
    implements _i12.CreateInternalBookingUseCase {
  MockCreateInternalBookingUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.DashboardRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeDashboardRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.DashboardRepository);

  @override
  _i7.Future<_i5.Either<_i13.Failure, _i14.Booking>> call(
    Map<String, dynamic>? bookingData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [bookingData]),
            returnValue:
                _i7.Future<_i5.Either<_i13.Failure, _i14.Booking>>.value(
                  _FakeEither_3<_i13.Failure, _i14.Booking>(
                    this,
                    Invocation.method(#call, [bookingData]),
                  ),
                ),
          )
          as _i7.Future<_i5.Either<_i13.Failure, _i14.Booking>>);
}

/// A class which mocks [GetAdminCourtsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAdminCourtsUseCase extends _i1.Mock
    implements _i15.GetAdminCourtsUseCase {
  MockGetAdminCourtsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.DashboardRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeDashboardRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.DashboardRepository);

  @override
  _i7.Future<_i5.Either<_i13.Failure, List<_i16.AdminSportCenterCourts>>> call(
    _i17.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i7.Future<
                  _i5.Either<_i13.Failure, List<_i16.AdminSportCenterCourts>>
                >.value(
                  _FakeEither_3<
                    _i13.Failure,
                    List<_i16.AdminSportCenterCourts>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i7.Future<
            _i5.Either<_i13.Failure, List<_i16.AdminSportCenterCourts>>
          >);
}
